version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18  # Updated to Node.js 18 (LTS)
    commands:
      - echo "Installing dependencies..."
      - npm install --legacy-peer-deps  # Workaround for peer dependency issues
      - npm audit fix --force  # Auto-fix vulnerabilities

  pre_build:
    commands:
      - echo "Running tests..."
      - CI=true npm test  # Force test execution in CI mode

  build:
    commands:
      - echo "Building React app..."
      - npm run build

  post_build:
    commands:
      - echo "Build completed on $(date)"
      - echo "Logging into ECR..."
      - aws ecr get-login-password | docker login --username AWS --password-stdin 101861531743.dkr.ecr.us-east-1.amazonaws.com
      - echo "Building Docker image..."
      - docker build -t todo-frontend .
      - echo "Tagging and pushing to ECR..."
      - docker tag todo-frontend:latest 101861531743.dkr.ecr.us-east-1.amazonaws.com/todo-frontend:latest
      - docker push 101861531743.dkr.ecr.us-east-1.amazonaws.com/todo-frontend:latest

cache:
  paths:
    - node_modules/**/*  # Cache to speed up future builds

artifacts:
  files:
    - 'build/**/*'  # Only needed if you want to archive build output
