version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running tests...
      - npm test
  build:
    commands:
      - echo Building application...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing Docker image to ECR...
      - $(aws ecr get-login --no-include-email)
      - docker build -t react-frontend .
      - docker tag react-frontend:101861531743.dkr.ecr.us-east-1.amazonaws.com/react-frontend:latest
      - docker push 101861531743.dkr.ecr.us-east-1.amazonaws.com/react-frontend:latest

artifacts:
  files:
    - '**/*'
  base-directory: 'build'
